require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserInputsController do

  # This should return the minimal set of attributes required to create a valid
  # UserInput. As you add validations to UserInput, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "body" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserInputsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user_inputs as @user_inputs" do
      user_input = UserInput.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_inputs).should eq([user_input])
    end
  end

  describe "GET show" do
    it "assigns the requested user_input as @user_input" do
      user_input = UserInput.create! valid_attributes
      get :show, {:id => user_input.to_param}, valid_session
      assigns(:user_input).should eq(user_input)
    end
  end

  describe "GET new" do
    it "assigns a new user_input as @user_input" do
      get :new, {}, valid_session
      assigns(:user_input).should be_a_new(UserInput)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_input as @user_input" do
      user_input = UserInput.create! valid_attributes
      get :edit, {:id => user_input.to_param}, valid_session
      assigns(:user_input).should eq(user_input)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserInput" do
        expect {
          post :create, {:user_input => valid_attributes}, valid_session
        }.to change(UserInput, :count).by(1)
      end

      it "assigns a newly created user_input as @user_input" do
        post :create, {:user_input => valid_attributes}, valid_session
        assigns(:user_input).should be_a(UserInput)
        assigns(:user_input).should be_persisted
      end

      it "redirects to the created user_input" do
        post :create, {:user_input => valid_attributes}, valid_session
        response.should redirect_to(UserInput.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_input as @user_input" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserInput.any_instance.stub(:save).and_return(false)
        post :create, {:user_input => { "body" => "invalid value" }}, valid_session
        assigns(:user_input).should be_a_new(UserInput)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserInput.any_instance.stub(:save).and_return(false)
        post :create, {:user_input => { "body" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_input" do
        user_input = UserInput.create! valid_attributes
        # Assuming there are no other user_inputs in the database, this
        # specifies that the UserInput created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserInput.any_instance.should_receive(:update).with({ "body" => "MyText" })
        put :update, {:id => user_input.to_param, :user_input => { "body" => "MyText" }}, valid_session
      end

      it "assigns the requested user_input as @user_input" do
        user_input = UserInput.create! valid_attributes
        put :update, {:id => user_input.to_param, :user_input => valid_attributes}, valid_session
        assigns(:user_input).should eq(user_input)
      end

      it "redirects to the user_input" do
        user_input = UserInput.create! valid_attributes
        put :update, {:id => user_input.to_param, :user_input => valid_attributes}, valid_session
        response.should redirect_to(user_input)
      end
    end

    describe "with invalid params" do
      it "assigns the user_input as @user_input" do
        user_input = UserInput.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserInput.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_input.to_param, :user_input => { "body" => "invalid value" }}, valid_session
        assigns(:user_input).should eq(user_input)
      end

      it "re-renders the 'edit' template" do
        user_input = UserInput.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserInput.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_input.to_param, :user_input => { "body" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_input" do
      user_input = UserInput.create! valid_attributes
      expect {
        delete :destroy, {:id => user_input.to_param}, valid_session
      }.to change(UserInput, :count).by(-1)
    end

    it "redirects to the user_inputs list" do
      user_input = UserInput.create! valid_attributes
      delete :destroy, {:id => user_input.to_param}, valid_session
      response.should redirect_to(user_inputs_url)
    end
  end

end
